# -*- coding: utf-8 -*-
"""eeg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JvsyBNWDnGw99x6Zkt8yMyXoWcTB0ZL-
"""

import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import welch
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# Models
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

st.title("🧠 EEG Stress Detection App")

# ---------------- FILE UPLOAD ----------------
uploaded_file = st.file_uploader("Upload EEG CSV File", type=["csv"])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)

    st.success("✅ File loaded successfully!")
    st.write("Shape:", df.shape)

    # ---------------- DATA CLEANING ----------------
    df = df.apply(pd.to_numeric, errors='coerce')
    df = df.dropna(axis=1, how='all')
    df = df.ffill().bfill()

    if 'Time' in df.columns:
        df = df.drop(columns=['Time'])

    eeg_channels = df.select_dtypes(include=[np.number])

    # ---------------- FEATURE EXTRACTION ----------------
    def extract_features(signal, fs=256):
        freqs, psd = welch(signal, fs, nperseg=len(signal))

        def band_power(fmin, fmax):
            idx = (freqs >= fmin) & (freqs <= fmax)
            return np.sum(psd[idx])

        return [
            band_power(0.5, 4),
            band_power(4, 8),
            band_power(8, 13),
            band_power(13, 30)
        ]

    # ---------------- DATASET ----------------
    X, y = [], []
    window_size = 64
    step = 32

    for col in eeg_channels.columns:
        signal = eeg_channels[col].values

        if len(signal) < window_size:
            continue

        for i in range(0, len(signal) - window_size, step):
            window = signal[i:i+window_size]
            features = extract_features(window)

            X.append(features)

            if features[3] > features[2]:
                y.append(1)
            else:
                y.append(0)

    X = np.array(X)
    y = np.array(y)

    st.write("Total samples:", len(X))

    # ---------------- TRAIN TEST ----------------
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # ---------------- MODELS ----------------
    models = {
        "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
        "Decision Tree": DecisionTreeClassifier(),
        "SVM": SVC(),
        "KNN": KNeighborsClassifier()
    }

    results = {}

    st.subheader("📊 Model Results")

    for name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        acc = accuracy_score(y_test, y_pred)
        results[name] = acc

        st.write(f"### {name}")
        st.write("Accuracy:", acc)
        st.text(classification_report(y_test, y_pred))

    best_model_name = max(results, key=results.get)
    st.success(f"🏆 Best Model: {best_model_name}")

    # =========================================================
    # 📊 GRAPHS
    # =========================================================

    st.subheader("📈 Visualizations")

    # 1️⃣ EEG Signal
    fig1 = plt.figure()
    plt.plot(eeg_channels.iloc[:500, 0])
    plt.title("EEG Signal (Sample)")
    plt.xlabel("Time")
    plt.ylabel("Amplitude")
    st.pyplot(fig1)

    # 2️⃣ Band Power
    sample = eeg_channels.iloc[:window_size, 0].values
    features = extract_features(sample)

    bands = ['Delta', 'Theta', 'Alpha', 'Beta']

    fig2 = plt.figure()
    plt.bar(bands, features)
    plt.title("EEG Band Power")
    st.pyplot(fig2)

    # 3️⃣ Class Distribution
    counts = np.bincount(y)

    fig3 = plt.figure()
    plt.bar(['Relaxed', 'Stress'], counts)
    plt.title("Class Distribution")
    st.pyplot(fig3)

    # 4️⃣ Beta Distribution
    fig4 = plt.figure()
    plt.hist(X[:, 3], bins=30)
    plt.title("Beta Band Distribution")
    st.pyplot(fig4)

    # 5️⃣ Model Comparison
    fig5 = plt.figure()
    plt.bar(results.keys(), results.values())
    plt.title("Model Accuracy Comparison")
    st.pyplot(fig5)